name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

<<<<<<< HEAD
      - name: List output
        run: ls -la dist
=======
      - name: List root directory
        run: ls -la

      - name: List build directory
        run: ls -la build
>>>>>>> 12c8c1d (Pages (#8))

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
<<<<<<< HEAD
          path: dist
=======
          path: build
>>>>>>> 12c8c1d (Pages (#8))

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
<<<<<<< HEAD
      url: 'https://lpchaing.github.io/Babel-Room/'
=======
      url: 'https://lpchaing.github.io/Babel-Room/' # Fix env var syntax
>>>>>>> 12c8c1d (Pages (#8))

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy
        uses: actions/deploy-pages@v4
